# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.12.0
    working_directory: ~/repo
    steps:
    - checkout
    # Download and cache dependencies
    - restore_cache:
        keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
    - run: yarn install
    - save_cache:
        paths:
        - node_modules
        key: yarn-packages-{{ checksum "yarn.lock" }}

    # run tests!
#    - run: yarn test

    - persist_to_workspace:
        root: .
        paths: repo

  deploy:
    docker:
    - image: circleci/node:10.12.0
    parallelism: 1
    working_directory: ~/repo
    steps:
    - checkout
    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run: yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "yarn.lock" }}
    - run: yarn build
    - run:
        name: Deploy to hosting
        # Package bundle and drop copy it to hosting
        command: |
          tar -czf dist.tar.gz dist
          sudo apt install sshpass
          sshpass -p '{{ .Environment.DEPLOY_PASSWORD }}' scp dist.tar.gz {{ .Environment.DEPLOY_USER }}@{{ .Environment.DEPLOY_URL }}:~/tmp
          sshpass -p '{{ .Environment.DEPLOY_PASSWORD }}' ssh {{ .Environment.DEPLOY_USER }}@{{ .Environment.DEPLOY_URL }}
          rm -rf {{ .Environment.DEPLOY_PATH }}/*
          ~/tmp
          tar -xzf ~/tmp/dist.tar.gz -C {{ .Environment.DEPLOY_PATH }}

workflows:
  version: 2
  build-and-deploy:
    jobs:
#      - build
      - deploy
#          requires:
#            - build
#          filters:
#            branches:
#              only: master
